# source: 
# 
# zf190904.1533

version: '3'

services:
    oc-ansible:
        build: .
        image: zubuntu
        container_name: oc-ansible
        restart: always
        volumes:
            - .:/host
            - /keybase:/keybase
            - .:/home/ubuntu/host
            - ./dev:/home/ubuntu/dev
            - ./ssh:/home/ubuntu/.ssh
        ports:
            - "127.0.0.1:52222:22"
        stdin_open: true
        tty: true


